# Generated by Django 3.0.3 on 2022-05-15 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FileDetailInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_title', models.CharField(max_length=50)),
                ('file_upload', models.DateField(default=django.utils.timezone.now)),
                ('file_url', models.FileField(upload_to='directory/')),
                ('guest_name', models.CharField(max_length=50)),
                ('owner_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_date', models.DateField(default=django.utils.timezone.now)),
                ('comment_text', models.TextField()),
                ('comment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('file_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cloud.FileDetailInfo')),
            ],
        ),
    ]
