# Generated by Django 3.0.3 on 2022-05-15 14:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0002_auto_20220515_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetailinfo',
            name='file_upload',
            field=models.DateField(default=datetime.datetime(2022, 5, 15, 14, 37, 46, 100066, tzinfo=utc)),
        ),
    ]
