# Generated by Django 3.0.3 on 2022-05-15 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_auto_20220515_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetailinfo',
            name='file_upload',
            field=models.DateField(default=datetime.datetime(2022, 5, 15, 23, 39, 17, 935107)),
        ),
    ]
