# Generated by Django 3.0.3 on 2022-05-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0007_auto_20220515_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetailinfo',
            name='file_upload',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='filedetailinfo',
            name='file_url',
            field=models.FileField(upload_to='directory/'),
        ),
        migrations.AlterField(
            model_name='filedetailinfo',
            name='guest_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
