# Generated by Django 3.0.3 on 2022-05-15 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0008_auto_20220515_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filedetailinfo',
            name='file_upload',
            field=models.DateField(verbose_name=django.utils.timezone.now),
        ),
    ]
